filename = "file.tsx"
invalid = [
	"<article role='article'></article>",
	"<button role='button'></button>",
	"<h1 role='heading' aria-level='1'></h1>",
	"<h1 role='heading'></h1>",
	"<dialog role='dialog'></dialog>",
	"<input\ttype='checkbox' role='checkbox' />",
	"<figure\trole='figure'></figure>",
	"<form\trole='form'></form>",
	"<table\trole='grid'></table>",
	"<td\trole='gridcell'></td>",
	"<fieldset\trole='group'></fieldset>",
	"<img src='foo' alt='bar'\trole='img' />",
	"<a role='link'></a>",
	"<link role='link' />",
	"<ol role='list' ></ol>",
	"<ul role='list' ></ul>",
	"<select role='listbox' ></select>",
	"<li role='listitem' ></li>",
	"<nav role='navigation' ></nav>",
	"<option role='option' ></option>",
	"<tr role='row' ></tr>",
	"<tbody role='rowgroup' ></tbody>",
	"<tfoot role='rowgroup' ></tfoot>",
	"<thead role='rowgroup' ></thead>",
	"<th scope='row' role='rowheader' ></th>",
	"<input type='search' role='searchbox' />",
	"<table role='table' ></table>",
	"<dt role='term' ></dt>",
	"<textarea role='textbox' ></textarea>",
	"<input type='text' role='textbox' />",
]
valid = [
	"<article role='presentation' ></article>",
	"<Button role='button' ></Button>",
	"<span></span>",
]
